apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factory
labels:
  - pairs:
      app.kubernetes.io/name: console
      app.kubernetes.io/part-of: software-factory
    includeSelectors: true
resources:
  - deployment.yaml
  - service.yaml
