apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- digest: sha256:10068c5b66e58a608b370b2f29ef672a13e399c521d5af7d034bb23656366c9f
  name: console
  newName: ghcr.io/mrogan/cv-software-factory/console
