apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- digest: sha256:387db01c320098cdde4981c9cd86db2cbea355723d5a2bdc9f84fd13051172e6
  name: console
  newName: ghcr.io/mrogan/cv-software-factory/console
